server.port=${PORT:8080}

logging.level.org.atmosphere=warn

vaadin.launch-browser=true

vaadin.allowed-packages=com.vaadin,org.vaadin,com.flowingcode,com.azaan

spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=jdbc:mysql://sql.freedb.tech:3306/freedb_FPdnI2hr
spring.datasource.username=u_riSdPi
spring.datasource.password=qH6XIRWWYm8Q
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

